spring.datasource.url=jdbc:postgresql://localhost:5432/graduate_work
spring.datasource.username=Admin
spring.datasource.password=Admin

server.port=8080

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

logging.level.ru.skypro.homework=DEBUG
logging.level.org.springframework.security=DEBUG

spring.web.cors.allowed-origins=http://localhost:3000

springdoc.swagger-ui.enabled=true 