spring.datasource.url=jdbc:postgresql://localhost:5432/graduate_work
spring.datasource.username=Admin
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

liquibase.change-log=classpath:/db.changelog-master.yaml